# Generated by Django 3.0.6 on 2020-07-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Widgets',
            new_name='Widget',
        ),
    ]
